# NUMPY Tutorial

In [10]:
import numpy as np
x= [1, 2, 3, 4, 5]
y= [1.67, 1.78, 1.56, 1.89, 1.34]
X = np.log(x)
Y = np.log(y)
slope, intercept = np.polyfit(X, Y, 1)
print(slope)

-0.07238694776263069


# 1D array

In [11]:
mylist = [1, 2, 3, 4, 5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


# 2D array

In [16]:
mylist2=[10, 20, 30, 40, 50]
myarray2D = np.array([mylist, mylist2])
print(myarray2D) 

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


# dimesions of the array

In [19]:
print(myarray.shape)
print(myarray2D.shape)

(5,)
(2, 5)


# find the datatype

In [20]:
print(myarray2D.dtype)

int64


# create zero array

In [25]:
zero_array = np.zeros(5) #5 coulmns zero array
print(zero_array)
zero_array2D = np.zeros([5, 5]) #5 coulmns zero array
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#create ones array
one_array = np.ones(5) #5 coulmns zero array
print(one_array)
one_array2D = np.ones([5, 5]) #5 coulmns zero array
print(one_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
#create empty array 
empty_array = np.empty(5) #5 coulmns zero array
print(empty_array)
empty_array2D = np.empty([5, 5]) #5 coulmns zero array
print(empty_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Identity array, diagonal values are 1

In [30]:
Identity_array = np.eye(3)
print(Identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array creation and initialization function

In [33]:
AP_array = np.arange(0, 50, 2)
print(AP_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


# scalar operation in numpy array

In [35]:
#scalar array multiplication using *
myarray2D = np.array([mylist, mylist2])
arr2 = myarray2D * myarray2D
print(arr2)

[[   1    4    9   16   25]
 [ 100  400  900 1600 2500]]


In [36]:
#exponential multiplication- suing ** operator
arr3 = myarray2D**3
print(arr3)

[[     1      8     27     64    125]
 [  1000   8000  27000  64000 125000]]


In [37]:
#scalar substraction
arr4 = arr3-arr2
print(arr4)


[[     0      4     18     48    100]
 [   900   7600  26100  62400 122500]]


In [38]:
#scalar division
arr5 = 1/arr2
print(arr5)

[[1.00000000e+00 2.50000000e-01 1.11111111e-01 6.25000000e-02
  4.00000000e-02]
 [1.00000000e-02 2.50000000e-03 1.11111111e-03 6.25000000e-04
  4.00000000e-04]]


# Numpy array Index

In [39]:
import numpy as np
arr = np.arange(100, 160, 2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [42]:
#access to individual array elements
#first element
print(arr[0])

100


In [44]:
#slicing the array
print(arr[0:5:1])

[100 102 104 106 108]


In [45]:
#updating array using slicing
arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [51]:
#creating new array slicing the old one
arr_new= arr[4:8]
print(arr_new)
#replacing the old values
arr_new[:] = 1
print(arr_new)

[1 1 1 1]
[1 1 1 1]


In [52]:
#after slicing and replacing of the old values will be saved to the old memory allocations for the mothre array
print(arr)

[  0   0   0   0   1   1   1   1 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [54]:
# copy functtion() to create new numpy memory
arr_new2= arr.copy()
arr_new2[:] = 0 # all values are zero
print(arr_new2)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   0   0   0   1   1   1   1 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


# Array indexes in Multidimensional array

In [66]:
#accessing row
#accessing the element of the array
mylist = [1, 2, 3, 4, 5]
mylist2=[10, 20, 30, 40, 50]
mylist3=[100, 200, 300, 400, 500]
myarray2D = np.array([mylist, mylist2, mylist3])
print(myarray2D)
print(myarray2D[0])
print(myarray2D[1])
print(myarray2D[0][2]) #row index, column index

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
[1 2 3 4 5]
[10 20 30 40 50]
3


In [65]:
#slicing in 2D arrays
slice1= myarray2D[0:1, 0:2] # first row(0), first 2 columns
print(slice1)

[[1 2]]


In [69]:
slice2= myarray2D[0:2, 0:3] # first two rows, first 3 columns
print(slice2)

[[ 1  2  3]
 [10 20 30]]


In [71]:
slice3 = myarray2D[:2, :3] #print until 2 rows and 3 coulmns 
print(slice3)

[[ 1  2  3]
 [10 20 30]]


# loop the index of array

In [75]:
arr_len= myarray2D.shape
print(arr_len)
nrows = arr_len[0]
print(nrows)

(3, 5)
3


In [76]:
for i in range(nrows):
    myarray2D[i][0] = i #replacing the first column with index of nrows
print(myarray2D)    

[[  0   2   3   4   5]
 [  1  20  30  40  50]
 [  2 200 300 400 500]]


# accessing the rows using index value

In [80]:
print(myarray2D[[0,1]]) # print first two row

[[ 0  2  3  4  5]
 [ 1 20 30 40 50]]


In [82]:
print(myarray2D[[1,0]]) # print first two row in reverse

[[ 1 20 30 40 50]
 [ 0  2  3  4  5]]


# Premium  Array operations

In [91]:
A=np.arange(15)
print(A)
B=np.arange(5, 10)
print(B)
C=np.arange(5, 10, 2)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]
[5 7 9]


In [88]:
# functions of numpy
#np.sqrt()
#np.log()
#np.polyfit()
#np.exp()
#np.add()
#np.maximum()
#np.minimum

#np.random.randn()

D = np.random.randn(5, 5)
print(D)

[[ 0.3554935   0.29202367 -1.02299764 -1.03310294 -1.76714807]
 [-0.17887727  1.40717106 -0.42228007 -1.69242525 -0.72321102]
 [-1.02116418  0.28000588  0.8088085  -2.34777373 -1.23877517]
 [ 0.10121865 -0.2771494  -0.32974805 -0.64261193 -0.14172739]
 [-2.57887881  2.04264003 -2.07549267 -1.08601687 -0.10143377]]


In [93]:
A = np.random.randn()
B = np.random.randn()
H = np.maximum(A, B)
print(H)

-1.282957842854356


# loading and saving arrays

In [96]:
import numpy as np
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [97]:
#saving single array
np.save("Saved_array", arr)

In [98]:
#loading single array
load_array1 = np.load("saved_array.npy")
print(load_array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [102]:
#saving multiple array
arr1 = np.arange(200)
arr2 = np.arange(25)

np.savez("saved_archieve.npz", x=arr1, y=arr2)

#loading the array

load_npz=np.load("saved_archieve.npz")
print(load_npz["x"])
print(load_npz["y"])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [109]:
#saving array to text file and loading
arr2 = np.arange(25)
np.savetxt("myarray.csv", arr2,delimiter=',')
load_file = np.loadtxt("myarray.csv", delimiter=',')
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


# Conditional Clause

In [111]:
x = np.array([100, 400, -50, -40])
y = np.array([10, 15, 20, 25])
condition = np.array([True, True, False, False])
z = [a if cond else b for a,cond,b in zip(x, condition, y)]
print(z)

[100, 400, 20, 25]


In [114]:
#using np.where()---(condition, values for true, values for false)
z2 = np.where(condition, x, y)
print(z2)

z3 = np.where(x>0, 1, x) #(if x>0 then take value 1 else take the value of x)
print(z3)

[100 400  20  25]
[  1   1 -50 -40]


In [120]:
#standard function
print(x.sum())
print(x.mean())
print(x.std())


410
102.5
181.71062159378576


In [118]:
x2 = np.array([[2,3], [4,5]])
print(x2)

[[2 3]
 [4 5]]


In [119]:
print(x2.sum(0)) # sum of the rows for two coulmns

[6 8]


# Logical Operation

In [121]:
condition2 = np.array([True, False, True, False])

#OR
print(condition2.any())

#And
print(condition2.all())



True
False


# SORTING

In [126]:
unsorted = np.array([1, 4, 7, 10, 6, 3])
unsorted.sort()
print(unsorted)

#unique()
arr7=np.array(['liquid', 'gas', 'gas', 'solid'])
print(np.unique(arr7))

[ 1  3  4  6  7 10]
['gas' 'liquid' 'solid']


In [128]:
#check the content of array

print(np.in1d(['solid', 'gas', 'plasma'], arr7))

[ True  True False]
